name: Automated API tests using Postman CLI 🚀

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "28474463-12310301-e8ed-4b77-af97-685d67e11b85" -e "28474463-55ddc7a3-df88-4288-8898-1e03966ea960"
